version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_ENCRYPTION_KEY=mySuperSecretKey
      - WEBHOOK_URL=https://n8n-server.onrender.com/
    volumes:
      - ~/.n8n:/home/node/.n8n
